[package]
name = "art_theory_bot"
version = "0.1.0"
authors = ["Arthur Goldman <arthur@goldman-tribe.org>"]

[[bin]]
name = "final"
path = "src/main.rs"

[[bin]]
name = "just-generate"
path = "src/generator.rs"

[dependencies]
oauth-client = "0.3.2"
rand = "0.3.15"
twitter-api = "0.3.0"